"""Give the self-hosted GenSen Rounded TW fonts a small "hero" layer so
first-screen text no longer waits on the full ~290 KB-per-weight files.

The full fonts are already a ~1,200-glyph subset of the site's own characters
(only ~200 bytes/glyph left in round-CJK CFF outlines), so cutting more glyphs
out of them saves nothing. What still helps is ordering: the characters shown
on the first screen (nav, loader steps, hero title/role/description/chips) go
into their own tiny file per weight, which is preloaded and covers those
characters via `unicode-range`; the full file is declared first with no range
and is only fetched for characters outside the hero set (below-the-fold copy),
so it no longer blocks the first paint.

  GenSenRounded2TW-<w>.woff2       full font, unchanged, declared first
  GenSenRounded2TW-<w>-hero.woff2  hero characters only, declared last with
                                   an explicit unicode-range

Also writes src/styles/gensen-faces.css (the @font-face rules, imported by
portfolio.css and projects-tailwind.css). Re-run after changing hero / nav /
loader copy in src/i18n/translations.ts (from the repo root):
    python scripts/subset-fonts.py
Requires: pip install fonttools brotli
"""
import os
import re

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
FONT_DIR = os.path.join(ROOT, 'public', 'fonts', 'gensen-rounded-tw')
WEIGHT_CSS = {'EL': 200, 'L': 300, 'R': 400, 'M': 500, 'B': 700, 'H': 900}
# Text keys (src/i18n/translations.ts) visible on the first screen.
HERO_KEY = re.compile(r"\b((?:nav|loader|hero)_\w+):\s*(['\"`])((?:\.|(?!\2).)*)\2", re.S)


def hero_chars():
    with open(os.path.join(ROOT, 'src', 'i18n', 'translations.ts'), encoding='utf8') as f:
        src = f.read()
    chars = set()
    for m in HERO_KEY.finditer(src):
        chars.update(m.group(3))
    chars |= {chr(c) for c in range(0x20, 0x7F)}       # ASCII
    chars |= {chr(c) for c in range(0x3000, 0x3040)}   # CJK punctuation
    chars |= {chr(c) for c in range(0xFF00, 0xFFF0)}   # full-width forms
    chars |= {chr(c) for c in range(0x2010, 0x2030)}   # dashes, quotes, ellipsis
    return {c for c in chars if c.isprintable()}


def unicode_range(chars):
    cps = sorted(ord(c) for c in chars)
    parts, start, prev = [], cps[0], cps[0]
    for cp in cps[1:] + [None]:
        if cp is not None and cp == prev + 1:
            prev = cp
            continue
        parts.append(f'U+{start:X}' if start == prev else f'U+{start:X}-{prev:X}')
        if cp is not None:
            start = prev = cp
    return ', '.join(parts)


def main():
    text = hero_chars()
    print(f'{len(text)} hero characters')
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['*']
    opts.notdef_outline = True
    opts.name_IDs = ['*']
    opts.hinting = False

    rng = unicode_range(text)
    css = ['/* GENERATED by scripts/subset-fonts.py -- do not edit by hand. */']
    for w, weight in WEIGHT_CSS.items():
        src = os.path.join(FONT_DIR, f'GenSenRounded2TW-{w}.woff2')
        dst = os.path.join(FONT_DIR, f'GenSenRounded2TW-{w}-hero.woff2')
        font = TTFont(src)
        sub = subset.Subsetter(opts)
        sub.populate(text=''.join(sorted(text)))
        sub.subset(font)
        font.flavor = 'woff2'
        font.save(dst)
        print(f'{w}: {os.path.getsize(src) // 1024} KB -> {os.path.getsize(dst) // 1024} KB')
        base = f'/fonts/gensen-rounded-tw/GenSenRounded2TW-{w}'
        for suffix, extra in (('.woff2', ''), ('-hero.woff2', f'\n  unicode-range: {rng};')):
            css.append(
                "@font-face {\n  font-family: 'GenSen Rounded TW';\n"
                f"  src: url('{base}{suffix}') format('woff2');\n"
                f'  font-weight: {weight};\n  font-style: normal;\n  font-display: swap;{extra}\n}}'
            )
    with open(os.path.join(ROOT, 'src', 'styles', 'gensen-faces.css'), 'w', encoding='utf8') as f:
        f.write('\n'.join(css) + '\n')


if __name__ == '__main__':
    main()
